### ISSUE TITLE
Como posso ajudar?

### ISSUE THREAD

**Issue by glaucia86** [braziljs/CodeLikeAGirl#1]
@AndrezaDeza uma dúvida, teria que abrir a Issue aqui e fazer a indicação das mulheres que ajudam e fazem a diferença nas Comunidades Técnicas? Se sim, posso enviar uma lista gigantesca aqui! rsrsrs

Um forte abraço,

Glaucia Lemos @glaucia86

**Comment by AndrezaDeza** [comment]
Oi Gláucia, publiquei sem desdobrar!
Vamos fazer varias issues :)
Uma de artigos, outra de blogs, canais, palestras... esse é o objetivo!

eu ja vi que tu fizestes bastante coisa sobre isso, minha ideia é na semana
que vem estar com tudo pronto pra divulgar e subir isso pro muuundo todoooo

Em sex, 22 de fev de 2019 às 17:11, Glaucia Lemos <notifications@github.com>
escreveu:

**Comment by glaucia86** [comment]
blz. Fechando essa issue aqui! Obrigada @AndrezaDeza
